server.error.include-message=always
###### RDBS via JPA #####
spring.jpa.orm=orm.xml
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
server.port=8090
server.ssl.enabled=false
server.servlet.context-path=/
# settings to enable CORS
cors.enabled=true
cors.allowedOrigins=*
#########################

###### SSL Bundle #######
#server.ssl.bundle=service
#spring.ssl.bundle.jks.service.key.alias=server
#spring.ssl.bundle.jks.service.keystore.location=classpath:keystore.p12
#spring.ssl.bundle.jks.service.keystore.password=password
#spring.ssl.bundle.jks.service.keystore.type=PKCS12
#########################

##### RDBS via JPA (in-memory H2) #####
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.profiles.active=jpa
#spring.datasource.driver=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#######################################

###### JPA (e.g. PostgresDB) #####
#spring.profiles.active=jpa
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.driver=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/fa3st-registry
#spring.datasource.username=fa3st-registry
#spring.datasource.password=ChangeMe
###############################################
