# EDC-CONNECTOR-CLIENT CONFIG
edc.controlplane.management.url=http://control-plane:8081/management/v3
edc.controlplane.auth.key.alias=api-key-control-plane

edc.aas.useAasDataplane=false
edc.aas.localAASServiceConfigPath=/resources/fa3st/config.json

# EDC CONFIG
edc.vault.hashicorp.health.check.enabled=true
edc.hostname=localhost
# Required to add participant to policies
# edc.participant.id=provider
web.http.port=8181
web.http.path=/api
web.http.default.auth.type=tokenbased
web.http.default.auth.key.alias=api-key-standalone

edc.web.rest.cors.enabled=true
edc.web.rest.cors.origins=*
edc.web.rest.cors.headers=*
edc.web.rest.cors.methods=GET, POST, DELETE, PUT, OPTIONS

edc.jsonld.https.enabled=true
