# EDC-CONNECTOR-CLIENT CONFIG
edc.controlplane.management.url=http://control-plane:8081/management/v3
edc.controlplane.auth.key.alias=api-key-control-plane

# This sets onlySubmodels=true, useAasDataPlane=false, exposeSelfDescription=false 
# and uses raw identifiable ids as asset id.
edc.aas.hercules=true
edc.aas.localAASServiceConfigPath=/resources/fa3st/config.json

# EDC CONFIG
# Vault
edc.vault.hashicorp.health.check.enabled=true
# Only for this runtime
edc.hostname=standalone
# Required to add participant to policies
edc.participant.id=did:web:identity-hub%3A10100:participant1
# Standalone API is exposed here
web.http.port=8181
web.http.path=/api
web.http.default.auth.type=tokenbased
web.http.default.auth.key.alias=api-key-standalone

edc.web.rest.cors.enabled=true
edc.web.rest.cors.origins=*
edc.web.rest.cors.headers=*
edc.web.rest.cors.methods=GET, POST, DELETE, PUT, OPTIONS

edc.jsonld.https.enabled=true
