services:
  provider:
    image: fraunhoferiosb/edc-extension4aas:latest
    ports:
      - "8181:8181"
      - "8281:8281"
      - "8182:8182"
      - "8282:8282"
    environment:
      EDC_FS_CONFIG: /config/provider-https.properties
    volumes:
      - ./config/edc:/config
      - ./resources:/resources
  consumer:
    image: fraunhoferiosb/edc-extension4aas:latest
    ports:
      - "9191:9191"
      - "9291:9291"
      - "9192:9192"
      - "9292:9292"
    environment:
      EDC_FS_CONFIG: /config/consumer.properties
    volumes:
      - ./config/edc:/config

  provider-dashboard:
    image: fraunhoferiosb/edc-extension4aas-dashboard:latest
    ports:
      - "4200:80"
    volumes:
      - ./config/dashboard/provider.nginx.conf:/etc/nginx/nginx.conf
      - ./config/dashboard/provider.json:/usr/share/nginx/html/assets/config/app.config.json

  consumer-dashboard:
    image: fraunhoferiosb/edc-extension4aas-dashboard:latest
    ports:
      - "4201:80"
    volumes:
      - ./config/dashboard/consumer.nginx.conf:/etc/nginx/nginx.conf
      - ./config/dashboard/consumer.json:/usr/share/nginx/html/assets/config/app.config.json