edc.hostname=identity-hub

# API
web.http.port=8181
web.http.path=/api
web.http.default.port=8181
web.http.default.path=/api

web.http.version.port=7171
web.http.version.path=/.well-known/api

web.http.credentials.port=13131
web.http.credentials.path=/api/credentials

web.http.did.port=10100
web.http.did.path=/

web.http.identity.port=15151
web.http.identity.path=/api/identity

web.http.sts.port=9292
web.http.sts.path=/api/sts
edc.iam.sts.token.expiration=5

edc.iam.accesstoken.jti.validation=false
edc.iam.credential.revocation.cache.validity=900000
edc.iam.credential.revocation.mimetype=*/*

# Identity
edc.participant.id=did:web:identity-hub%3A10100
edc.iam.did.web.use.https=false
# SuperUser Extension
edc.ih.api.superuser.id=admin
edc.ih.api.superuser.key=YWRtaW4=.s3cr3t
edc.ih.issuer.demonstrator.scope=org.factoryx.vc.type

# Persistence
edc.datasource.default.url=jdbc:postgresql://postgres:5432/identity_hub
edc.sql.schema.autocreate=true

# Vault
edc.vault.hashicorp.health.check.enabled=true

# Without this, an AES key needs to be put into the vault -> edc.encryption.aes.key.alias
edc.encryption.strict=false
