java.tool.options=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005

##################
### EDC Config ###
##################

edc.hostname=issuer-service
edc.participant.id=did:web:issuer-service

#################
# API Endpoints #
#################
web.http.default.port=8181
web.http.default.path=/api
web.http.port=8181
web.http.path=/api

web.http.statuslist.port=9999
web.http.statuslist.path=/statuslist

web.http.did.port=10100
web.http.did.path=/

web.http.issuance.port=13132
web.http.issuance.path=/api/issuance

web.http.identity.port=15151
web.http.identity.path=/api/identity

web.http.issueradmin.port=15152
web.http.issueradmin.path=/api/issuer

web.http.sts.port=9292
web.http.sts.path=/api/sts

web.http.version.port=7171
web.http.version.path=/.well-known/api

####################
# Identity-related #
####################

edc.iam.did.web.use.https=false
edc.ih.api.superuser.id=admin
edc.ih.api.superuser.key=YWRtaW4=.s3cr3t
edc.ih.issuer.demonstrator.scope=org.factoryx.vc.type

# Persistence
edc.datasource.default.url.alias=does_not_exist
edc.datasource.default.url=jdbc:postgresql://postgres:5432/issuer_service
edc.sql.schema.autocreate=true

# Vault
edc.vault.hashicorp.health.check.enabled=true

##########################
# Issuer-Service-related #
##########################

edc.statuslist.callback.address=http://issuer-service:9999/statuslist
edc.issuer.statuslist.signing.key.alias=default
edc.ih.issuer.demonstrator.defaultconfig=/app/setup.json
edc.issuer.issuance.send.retry.limit=0
