server.error.include-message=always

spring.jpa.orm=orm.xml
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

server.port=8090
server.ssl.enabled=false

server.servlet.context-path=/

cors.enabled=true
cors.allowedOrigins=*
