# Note: this logging.properties file is used for all EDC-related components
handlers=java.util.logging.ConsoleHandler

# Console Handler Config

java.util.logging.ConsoleHandler.formatter=org.eclipse.tractusx.identityhub.monitor.ColorfulFormatter
java.util.logging.ConsoleHandler.level=FINE

# Formatter Configs
org.eclipse.tractusx.identityhub.monitor.ColorfulFormatter.format=%7$s[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$s] %5$s%6$s%n%8$s

# Root level and Package level control
.level=INFO
jakarta.json.level=WARNING
jdk.event.level=WARNING
okhttp3.internal.level=WARNING
org.flywaydb.level=WARNING
org.glassfish.level=WARNING
org.jvnet.level=WARNING
org.postgresql.level=INFO

org.eclipse.edc.level=FINE
org.eclipse.edc.monitor.logger.LoggerMonitor.level=INFO
