# EDC CONFIG
edc.hostname=participant2

#################
# API Endpoints #
#################
web.http.port=8080
web.http.path=/api

web.http.management.port=8081
web.http.management.path=/management
web.http.management.auth.type=tokenbased
# Could (and should) also be done via vault secret.
web.http.management.auth.key.alias=api-key-control-plane

web.http.metrics.port=9090
web.http.metrics.path=/metrics
web.http.catalog.port=8085
web.http.catalog.path=/catalog

# Register dataplanes etc.
web.http.control.port=8083
web.http.control.path=/control
edc.control.endpoint=http://participant2:8083/control

# Communication with other control-planes
web.http.protocol.port=8084
web.http.protocol.path=/api/v1/dsp
# Give this address as negotiation endpoint:
edc.dsp.callback.address=http://participant2:8084/api/v1/dsp

#################
#  Persistence  #
#################
edc.datasource.default.url=jdbc:postgresql://postgres:5432/participant2
edc.sql.schema.autocreate=true

# SQL Migration Extension REQUIRES these to be present in the config...
edc.datasource.default.user=postgres
edc.datasource.default.password=password

# Vault
edc.vault.hashicorp.health.check.enabled=true

####################
# Identity-related #
####################

# Participant, Issuer
edc.participant.id=did:web:identity-hub%3A10100:participant2
# Randomly generated context id
edc.participant.context.id=f2a26a4f-f153-4710-aa81-30efd8b2cffe
edc.iam.issuer.id=did:web:identity-hub%3A10100:participant2
# Add more issuers: edc.iam.trusted-issuer.<my-issuer>.id=<my-issuers-did>
edc.iam.trusted-issuer.issuer-service.id=did:web:issuer-service%3A10100
edc.iam.credential.revocation.mimetype=application/json

# STS
edc.iam.sts.oauth.token.url=http://identity-hub:8087/api/sts/token
edc.iam.sts.oauth.client.id=did:web:identity-hub%3A10100:participant2
# Note: this secret is generated by the init.sh script inside the toolbox container
edc.iam.sts.oauth.client.secret.alias=participant2-sts-client-secret

# Set to true if communication over official URLs happens
edc.iam.did.web.use.https=false

# GUI configuration (enable DataDashboard to communicate with EDC)
edc.web.rest.cors.enabled=true
edc.web.rest.cors.origins=*
edc.web.rest.cors.headers=x-api-key, content-type
edc.web.rest.cors.methods=GET, POST, DELETE, PUT, OPTIONS


# Register this connector at DID document:
tx.edc.did.service.self.registration.enabled=true
