edc.hostname=control-plane
# API
web.http.port=8080
web.http.path=/api

web.http.management.port=8081
web.http.management.path=/management
web.http.management.auth.type=tokenbased
# Could (and should) also be done via vault secret.
web.http.management.auth.key.alias=api-key-control-plane

web.http.metrics.port=9090
web.http.metrics.path=/metrics

web.http.catalog.port=8085
web.http.catalog.path=/catalog

# Register dataplanes etc.
web.http.control.port=8083
web.http.control.path=/control
edc.control.endpoint=http://control-plane:8083/control

# Communication with other control-planes
web.http.protocol.port=8084
web.http.protocol.path=/api/v1/dsp
# Give this address as negotiation endpoint:
edc.dsp.callback.address=http://control-plane:8084/api/v1/dsp

#  Persistence
edc.sql.schema.autocreate=true
# SQL Migration Extension REQUIRES these to be present in the config...
edc.datasource.default.url=jdbc:postgresql://postgres:5432/edc
edc.datasource.default.user=postgres
edc.datasource.default.password=password

# Vault
edc.vault.hashicorp.health.check.enabled=true

# Identity-related
# Participant
edc.participant.id=did:web:identity-hub%3A10100:participant1
# Randomly generated context id
edc.participant.context.id=did:web:identity-hub%3A10100:participant1
edc.iam.issuer.id=did:web:identity-hub%3A10100:participant1
# STS
edc.iam.sts.oauth.token.url=http://identity-hub:9292/api/sts/token
edc.iam.sts.oauth.client.id=did:web:identity-hub%3A10100:participant1
# Note: this secret is generated by the init.sh script inside the toolbox container
edc.iam.sts.oauth.client.secret.alias=participant1-sts-client-secret
edc.iam.did.web.use.https=false
edc.iam.accesstoken.jti.validation=false
# Issuer
# Add more issuers: edc.iam.trusted-issuer.<my-issuer>.id=<my-issuers-did>
edc.iam.trusted-issuer.issuer-service.id=did:web:issuer-service%3A10100
edc.iam.credential.revocation.mimetype=application/json

# CORS
edc.web.rest.cors.enabled=true
edc.web.rest.cors.origins=*
edc.web.rest.cors.headers=x-api-key, content-type
edc.web.rest.cors.methods=GET, POST, DELETE, PUT, OPTIONS

# Register this connector at DID document:
tx.edc.did.service.self.registration.enabled=true
tx.edc.postgresql.migration.asset.enabled=false
tx.edc.postgresql.migration.agreementbpns.enabled=false
tx.edc.postgresql.migration.bpn.enabled=false
tx.edc.postgresql.migration.contractdefinition.enabled=false
tx.edc.postgresql.migration.contractnegotiation.enabled=false
tx.edc.postgresql.migration.dataplaneinstance.enabled=false
tx.edc.postgresql.migration.edr.enabled=false
tx.edc.postgresql.migration.federatedcatalog.enabled=false
tx.edc.postgresql.migration.jti-validation.enabled=false
tx.edc.postgresql.migration.policy-monitor.enabled=false
tx.edc.postgresql.migration.policy.enabled=false
tx.edc.postgresql.migration.transferprocess.enabled=false

tx.edc.iam.iatp.default-scopes.MembershipCredential.alias=org.eclipse.tractusx.vc.type
tx.edc.iam.iatp.default-scopes.MembershipCredential.type=MembershipCredential
tx.edc.iam.iatp.default-scopes.MembershipCredential.operation=read
